CREATE TABLE TASK (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    IS_COMPLETED BOOLEAN
);

INSERT INTO TASK(ID, TITLE, DESCRIPTION, IS_COMPLETED)
VALUES (1, 'Kotlin para Backend', 'Desenvolvimento Backend', false)

INSERT INTO TASK(ID,TITLE, DESCRIPTION, ISCOMPLETED)
VALUES (2, 'Linguagem Python', 'Desenvolvimento Backend', false)
