CREATE TABLE TASK(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ISCOMPLETED BOOLEAN
);

INSERT INTO TASK(TITLE, DESCRIPTION, ISCOMPLETEDS)
VALUES ('Kotlin para Backend', 'Desenvolvimento Backend', false)

INSERT INTO TASK(TITLE, DESCRIPTION, ISCOMPLETEDS)
VALUES ('Linguagem Python', 'Desenvolvimento Backend', false)